import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/layout/header";
import Footer from "./component/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
              rel="icon"
              href="/favicon.ico"
              type="image/x-icon"
              sizes="any"
            />
        <title>Cripto</title>
      </head>
      <body className={inter.className}>
        <div className="main-div">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
